name: Build Windows x64 prebuilds

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-windows-x64:
    name: Build Windows x64 (Node ${{ matrix.node }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16, 18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build native addon
        # relies on package.json "build" script (node-gyp rebuild)
        run: npm run build

      - name: Run error-handling tests
        run: node test/error_handling.test.js

      - name: Run tests
        run: npm test

      - name: Create prebuild artifact (x64)
        env:
          npm_config_disturl: https://nodejs.org/dist
        # Use PowerShell-safe commands on windows-latest and prefer the locally installed prebuild (no network fetch)
        run: |
          if (!(Test-Path prebuilds)) { New-Item -ItemType Directory -Path prebuilds | Out-Null }
          npx --no-install prebuild --strip --target ${{ matrix.node }} --arch=x64 --platform=win32 --runtime=node --out prebuilds

      - name: Upload prebuild artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuild-win-x64-node-${{ matrix.node }}
          path: prebuilds/*

      - name: Publish prebuild to GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: prebuilds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}