name: CI Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - node: "22.x"
            arch: "x64"
            runner: windows-latest
            platform: win32
          - node: "22.x"
            arch: "x64"
            runner: ubuntu-latest
            platform: linux
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps
        run: npm ci
      - name: Run unit tests
        run: npm test
